services:
  camera-control-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camera-control-core
    network_mode: host
    volumes:
      - ./main.py:/app/main.py
      - /tmp:/tmp
      - /run/user/1000/:/run/user/1000
    stdin_open: true
    tty: true
    depends_on:
      - weston

  weston:
    image: torizon/weston-imx8:4
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
      - /run/user/1000:/run/user/1000
    cap_add:
      - CAP_SYS_TTY_CONFIG
