services:
  camera-control-system:
    #image: arnobchanda/vpu-test-image:latest
    build:
       context: .
       dockerfile: Dockerfile
    container_name: camera-control-core
    privileged: true
    network_mode: host
    volumes:
      - ./main.py:/app/main.py
      - ./run.sh:/app/run.sh
      - /tmp:/tmp
      - /dev:/dev
      - /run/udev:/run/udev
    devices:
      - "/dev/cec0:/dev/cec0"
      - "/dev/fb0:/dev/fb0"
      - "/dev/galcore:/dev/galcore"
      - "/dev/mxc_hantro:/dev/mxc_hantro"
      - "/dev/mxc_hantro_vc8000e:/dev/mxc_hantro_vc8000e"
      - "/dev/video10:/dev/video10"
    stdin_open: true
    tty: true
    command: ["/bin/bash", "/app/run.sh"]
    # depends_on:
    #   - weston

  # weston:
  #   image: torizon/weston-imx8:4
  #   environment:
  #     - ACCEPT_FSL_EULA=1
  #   # Required to get udev events from host udevd via netlink
  #   network_mode: host
  #   privileged: true
  #   restart: always
  #   volumes:
  #     - type: bind
  #       source: /tmp
  #       target: /tmp
  #     - type: bind
  #       source: /dev
  #       target: /dev
  #     - type: bind
  #       source: /run/udev
  #       target: /run/udev
  #     - /run/user/1000:/run/user/1000
  #   cap_add:
  #     - CAP_SYS_TTY_CONFIG
